### ISSUE TITLE
New props not reflected in render

### ISSUE THREAD

**Issue by hhaidar** [oklas/react-breadcrumbs-dynamic#1]
Hi,

Prop changes for children aren't being displayed properly. I think there's a problem in `componentWillReceiveProps`.

Awesome component btw!

**Comment by oklas** [comment]
Hi

You are right, it's typo. I pass `props` instead of `nextProps` in `componentWillReceiveProps` so children props does not updated.

Thanks for taking notice. It is fixed in 1.0.4.

Feel free to reopen or open new if need.

**Comment by hhaidar** [comment]
Awesome! Thank you so much.
