### ISSUE TITLE
Compound final item

### ISSUE THREAD

**Issue by nWidart** [oklas/react-breadcrumbs-dynamic#17]
Hello,

Is it possible to have a compound item, as final item?

Example:

```
finalItem={'span > strong'}
```

Thanks

**Comment by oklas** [comment]
Yes, if I understand correctly, you can create a special component and provide it to `finalItem` or create anonimous component inplace like this:

```js
    finalItem={
      ({children}) => (
       <span><strong>{children}</strong></span>
      )
    }
```

Such questions better for stackoverflow, users frequently search answers there, and also it have feature: inviting to question. However this is good place too and any feedback and stars is very significant to know that my creations is on demand. Thereto followers can receive notifications about new features.

Now I close the issue. Feel free to write or reopen or create new if any.

**Comment by nWidart** [comment]
Thank you for the reply.

I don't agree with stackoverflow but sure.
