### ISSUE TITLE
How to hide breadcrumb on a page without breaking the trail

### ISSUE THREAD

**Issue by MuneebJS** [oklas/react-breadcrumbs-dynamic#18]
I have three pages
- Home (Don't need breadcrumbs)
- Products 
- Product Details
So, what I'm trying to achieve that to hide breadcrumb on the home page but other pages should have breadcrumb trail with **home link**.

**Comment by oklas** [comment]
If you need to hide breadcrums itself on some condition use this:

```js
    <Header>
      { condition ? <Breadcrumbs/> : null }
    </Header>
```

If you need to hide breadcrums item itself on some condition use this:

```js
    <Page>
      { condition ? <BreadcrumbsItem to='/page' /> : null }
    </Page>
```

If you mean some else please clarify. Let me know if it helps.

**Comment by oklas** [comment]
I close now. Feel free to reopen or create new,

**Comment by MuneebJS** [comment]
Thanks @oklas it worked.
