### ISSUE TITLE
Library doesn't have a native way to hide crumbs in case of no crumbs

### ISSUE THREAD

**Issue by FriOne** [oklas/react-breadcrumbs-dynamic#25]
So now I used `withBreadcrumbsContainer` to hide the container.
Any plans for this? I think `hideIfEmpty` props will be ok.

**Comment by oklas** [comment]
Hi! If I understand correctly, you suggests to add `hideIfEmpty` bool props which will render nothing if no one item available to render in breadcrumbs. Good. It will be excellent if you have time to do that also with additional tests of course. Or let me know if you busy then i will do that nearest days or some later.

**Comment by FriOne** [comment]
Not sure how to make tests right.

**Comment by tjugg** [comment]
Any update on this? :)
