### ISSUE TITLE
Use case without react router

### ISSUE THREAD

**Issue by colelogan** [oklas/react-breadcrumbs-dynamic#8]
Is their any examples that use this package but doesn't use react router. for example I want to make an app that uses react router but I don't want the url to change with the breadcrumbs. I want the path to show in the breadcrumbs not url.

**Comment by oklas** [comment]
It seems to me that the questions is more appropriate to stackoverflow. Could you please create question there and provide minimal code peace to make more clean what you mean. I will be glad to provide example when I will have some time if questin will be not answered yet. Please leave link here to your question.

**Comment by oklas** [comment]
You can show in breadcrumbs current url taken from react router like this:

```jsx
import { withRouter } from 'react-router'

const Test = ({location}) => (  
  <BreadcrumbsItem to={location.pathname}>Current path</BreadcrumbsItem>
)

export default withRouter(Test)
```

You can do same thing by vanilla js without react router like this:

```jsx
const Test = ({location}) => (  
  <BreadcrumbsItem to={window.location.href}>Current path</BreadcrumbsItem>
)
```

You can show in breadcrumbs any url like this:

```jsx
<BreadcrumbsItem to="https://example.org/test">Full url with path</BreadcrumbsItem>
<BreadcrumbsItem to="/test">Absolute path</BreadcrumbsItem>
<BreadcrumbsItem to="test">Relative path</BreadcrumbsItem>
```

If you need some another thing please reopen and clarify.
